"""create products table

Revision ID: fe74fd574118
Revises:
Create Date: 2026-10-02 10:14:40.392308

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe74fd574118"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "lock",
                "hinge",
                "closer",
                "exit_device",
                "power_supply",
                name="category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("manufacturer", sa.String(length=100), nullable=False),
        sa.Column("fire_rating_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "material",
            sa.Enum(
                "hollow_metal",
                "wood",
                "aluminum",
                "glass",
                name="material",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("electrified", sa.Boolean(), nullable=False),
        sa.Column("voltage", sa.Integer(), nullable=True),
        sa.Column("finish", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "fire_rating_minutes IN (0, 20, 45, 60, 90, 180)",
            name=op.f("ck_products_fire_rating_minutes"),
        ),
        sa.CheckConstraint("voltage > 0 AND voltage <= 48", name=op.f("ck_products_voltage_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
